services:
  catalogdb:
    container_name: catalogdb
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports: 
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433"

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce_mq
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=XMrx@1970
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/APP/ASPNET/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - /Microsoft/UserSecrets:/APP/Microsoft/usersecrets:ro
      - /ASP.NET/Https:/APP/ASPNET/https:ro 

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=XMrx@1970
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/APP/ASPNET/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl = https://discount.grpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__OrderFullfilment=false
    depends_on:
      - catalogdb
      - distributedcache
      - discount.grpc
      - messagebroker
      - orderdb
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - /Microsoft/UserSecrets:/APP/Microsoft/usersecrets:ro
      - /ASP.NET/Https:/APP/ASPNET/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=XMrx@1970
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/APP/ASPNET/https/aspnetapp.pfx
      - ConnectionStrings__Database=Data Source=discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - /Microsoft/UserSecrets:/APP/Microsoft/usersecrets:ro
      - /ASP.NET/Https:/APP/ASPNET/https:ro

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
